### ISSUE TITLE
My Computer went dead.

### ISSUE THREAD

**Issue by PointCloudNiphon** [ABadCandy/BaiDuBigData19-URFC#1]
help    !!!!
thinks for your kernnal, but...
My computer has a gpu GTX950m with a 4g memory, with the batchsize of 8(16+ dead in the beginning),when I finished the first epoch,  it did not  respond............ 

 and the training errror was less than 0.5...
I am hungry...

**Comment by ABadCandy** [comment]
Emm I think your computer's memory is a bit small, maybe you can try to set the batch_size=2，or crop the input image into 88*88.

**Comment by ABadCandy** [comment]
@PointCloudNiphon  I think your computer's memory is a bit small, maybe you can try to set the batch_size=2，or crop the input image into 88*88.

**Comment by PointCloudNiphon** [comment]
> @PointCloudNiphon I think your computer's memory is a bit small, maybe you can try to set the batch_size=2，or crop the input image into 88*88.

thanks ,follow your idea. your code worked, I want to know info about your GPU and time  a epoch costs

**Comment by ABadCandy** [comment]
@PointCloudNiphon I have tested it with two TITAN XP in docker,  but due to the limitations of docker's shared memory size, I have to set the num_workers=1 in Pytorch's DataLoader, so running an epoch just about 20 minutes. If you don't run it in docker, you can set the num_workers=16 or greater. Besides, you can try to fix the first convolution layers' weight and just finetune the last fully-connected layers to accelerate model training.

**Comment by PointCloudNiphon** [comment]
thanks，  following your idea ，setting num_works=3(other features added) costs me 30mins a epoch, I feel very happy...

**Comment by PointCloudNiphon** [comment]
### I used the tensorboard to visualize the training process, before .And I know just wait for a night ,things just happened.  But I am curious about your waiting...
